---
title: "ActivityMonitoring"
author: "Zinat Wali"
date: "Sunday, August 24, 2014"
output: html_document
---

```{r}
library(caret)
```


```{r cache=TRUE}
training <- read.csv('https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv')

test <- read.csv('https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv')
```


The training data is then copied into another data frame. The original one is kept for reference and fallback.

```{r cache=TRUE}
inTraining <- training
inTesting <- test
```


removing irrelevant features...

```{r}
LL <- c(1:7)

for(i in 8:ncol(inTraining))
{
  if(sum(!is.na(inTraining[, i]) && inTraining[,i] != '') == 0)
  {
    LL <- append(LL, i)
  }
}

inTraining <- inTraining[, -LL]

```

partitioning data....

```{r}

```

random forest...

```{r, echo=FALSE}
#rfFit <- randomForest(trainingSubSet[, -53], trainingSubSet[, 53], mtry=4)
##pRF <- predict(rfFit, testingSubSet)
#confusionMatrix(testingSubSet$classe, pRF)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
